import { ItemAllowOffHandComponent } from "./allow_off_hand.ts";
import { ItemBlockPlacerComponent } from "./block_placer.ts";
import { ItemBundleInteractionComponent } from "./bundle_interaction.ts";
import { ItemCanDestroyInCreativeComponent } from "./can_destroy_in_creative.ts";
import { ItemCompostableComponent } from "./compostable.ts";
import { ItemCooldownComponent } from "./cooldown.ts";
import { ItemDamageComponent } from "./damage.ts";
import { ItemDamageAbsorptionComponent } from "./damage_absorption.ts";
import { ItemDiggerComponent } from "./digger.ts";
import { ItemDisplayNameComponent } from "./display_name.ts";
import { ItemDurabilityComponent } from "./durability.ts";
import { ItemDurabilitySensorComponent } from "./durability_sensor.ts";
import { ItemDyeableComponent } from "./dyeable.ts";
import { ItemEnchantableComponent } from "./enchantable.ts";
import { ItemEntityPlacerComponent } from "./entity_placer.ts";
import { ItemFireResistantComponent } from "./fire_resistant.ts";
import { ItemFoodComponent } from "./food.ts";
import { ItemFuelComponent } from "./fuel.ts";
import { ItemGlintComponent } from "./glint.ts";
import { ItemHandEquippedComponent } from "./hand_equipped.ts";
import { ItemHoverTextColorComponent } from "./hover_text_color.ts";
import { ItemIconComponent } from "./icon.ts";
import { ItemInteractButtonComponent } from "./interact_button.ts";
import { ItemKineticWeaponComponent } from "./kinetic_weapon.ts";
import { ItemLiquidClippedComponent } from "./liquid_clipped.ts";
import { ItemMaxStackSizeComponent } from "./max_stack_size.ts";
import { ItemPiercingWeaponComponent } from "./piercing_weapon.ts";
import { ItemProjectileComponent } from "./projectile.ts";
import { ItemRarityComponent } from "./rarity.ts";
import { ItemRecordComponent } from "./record.ts";
import { ItemRepairableComponent } from "./repairable.ts";
import { ItemSeedComponent } from "./seed.ts";
import { ItemShooterComponent } from "./shooter.ts";
import { ItemShouldDespawnComponent } from "./should_despawn.ts";
import { ItemStackedByDataComponent } from "./stacked_by_data.ts";
import { ItemStorageItemComponent } from "./storage_item.ts";
import { ItemStorageWeightLimitComponent } from "./storage_weight_limit.ts";
import { ItemStorageWeightModifierComponent } from "./storage_weight_modifier.ts";
import { ItemSwingDurationComponent } from "./swing_duration.ts";
import { ItemSwingSoundsComponent } from "./swing_sounds.ts";
import { ItemTagsComponent } from "./tags.ts";
import { ItemThrowableComponent } from "./throwable.ts";
import { ItemUseAnimationComponent } from "./use_animation.ts";
import { ItemUseModifiersComponent } from "./use_modifiers.ts";
import { ItemWearableComponent } from "./wearable.ts";

/**
 * Type map for item component.
 */
export interface ItemComponentTypes {
  "minecraft:allow_off_hand": ItemAllowOffHandComponent;
  "minecraft:block_placer": ItemBlockPlacerComponent;
  "minecraft:bundle_interaction": ItemBundleInteractionComponent;
  "minecraft:can_destroy_in_creative": ItemCanDestroyInCreativeComponent;
  "minecraft:compostable": ItemCompostableComponent;
  "minecraft:cooldown": ItemCooldownComponent;
  "minecraft:damage": ItemDamageComponent;
  "minecraft:damage_absorption": ItemDamageAbsorptionComponent;
  "minecraft:digger": ItemDiggerComponent;
  "minecraft:display_name": ItemDisplayNameComponent;
  "minecraft:durability": ItemDurabilityComponent;
  "minecraft:durability_sensor": ItemDurabilitySensorComponent;
  "minecraft:dyeable": ItemDyeableComponent;
  "minecraft:enchantable": ItemEnchantableComponent;
  "minecraft:entity_placer": ItemEntityPlacerComponent;
  "minecraft:fire_resistant": ItemFireResistantComponent;
  "minecraft:food": ItemFoodComponent;
  "minecraft:fuel": ItemFuelComponent;
  "minecraft:glint": ItemGlintComponent;
  "minecraft:hand_equipped": ItemHandEquippedComponent;
  "minecraft:hover_text_color": ItemHoverTextColorComponent;
  "minecraft:icon": ItemIconComponent;
  "minecraft:interact_button": ItemInteractButtonComponent;
  "minecraft:kinetic_weapon": ItemKineticWeaponComponent;
  "minecraft:liquid_clipped": ItemLiquidClippedComponent;
  "minecraft:max_stack_size": ItemMaxStackSizeComponent;
  "minecraft:piercing_weapon": ItemPiercingWeaponComponent;
  "minecraft:projectile": ItemProjectileComponent;
  "minecraft:rarity": ItemRarityComponent;
  "minecraft:record": ItemRecordComponent;
  "minecraft:repairable": ItemRepairableComponent;
  "minecraft:seed": ItemSeedComponent;
  "minecraft:shooter": ItemShooterComponent;
  "minecraft:should_despawn": ItemShouldDespawnComponent;
  "minecraft:stacked_by_data": ItemStackedByDataComponent;
  "minecraft:storage_item": ItemStorageItemComponent;
  "minecraft:storage_weight_limit": ItemStorageWeightLimitComponent;
  "minecraft:storage_weight_modifier": ItemStorageWeightModifierComponent;
  "minecraft:swing_duration": ItemSwingDurationComponent;
  "minecraft:swing_sounds": ItemSwingSoundsComponent;
  "minecraft:tags": ItemTagsComponent;
  "minecraft:throwable": ItemThrowableComponent;
  "minecraft:use_animation": ItemUseAnimationComponent;
  "minecraft:use_modifiers": ItemUseModifiersComponent;
  "minecraft:wearable": ItemWearableComponent;
}
